#ifndef TINYOS_TRAP_H
#define TINYOS_TRAP_H

#include <stddef.h>

#include "trap_offsets.h"

typedef unsigned long u64;

struct trap_frame {
    u64 ra;
    u64 gp;
    u64 tp;

    u64 t0;
    u64 t1;
    u64 t2;

    u64 s0;
    u64 s1;

    u64 a0;
    u64 a1;
    u64 a2;
    u64 a3;
    u64 a4;
    u64 a5;
    u64 a6;
    u64 a7;

    u64 s2;
    u64 s3;
    u64 s4;
    u64 s5;
    u64 s6;
    u64 s7;
    u64 s8;
    u64 s9;
    u64 s10;
    u64 s11;

    u64 t3;
    u64 t4;
    u64 t5;
    u64 t6;

    u64 sp;

    u64 sepc;
    u64 sstatus;
    u64 scause;
    u64 stval;

    u64 reserved;
};

#define TRAP_FRAME_ASSERT_OFFSET(member, expected) \
    _Static_assert( \
        offsetof(struct trap_frame, member) == (expected), \
        "trap_frame." #member " offset must match trap_entry.S" \
    )

_Static_assert(
    sizeof(struct trap_frame) == TRAP_FRAME_SIZE,
    "trap_frame size must match trap_entry.S"
);

TRAP_FRAME_ASSERT_OFFSET(ra, TRAP_FRAME_RA_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(gp, TRAP_FRAME_GP_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(tp, TRAP_FRAME_TP_OFFSET);

TRAP_FRAME_ASSERT_OFFSET(t0, TRAP_FRAME_T0_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(t1, TRAP_FRAME_T1_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(t2, TRAP_FRAME_T2_OFFSET);

TRAP_FRAME_ASSERT_OFFSET(s0, TRAP_FRAME_S0_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(s1, TRAP_FRAME_S1_OFFSET);

TRAP_FRAME_ASSERT_OFFSET(a0, TRAP_FRAME_A0_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(a1, TRAP_FRAME_A1_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(a2, TRAP_FRAME_A2_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(a3, TRAP_FRAME_A3_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(a4, TRAP_FRAME_A4_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(a5, TRAP_FRAME_A5_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(a6, TRAP_FRAME_A6_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(a7, TRAP_FRAME_A7_OFFSET);

TRAP_FRAME_ASSERT_OFFSET(s2, TRAP_FRAME_S2_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(s3, TRAP_FRAME_S3_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(s4, TRAP_FRAME_S4_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(s5, TRAP_FRAME_S5_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(s6, TRAP_FRAME_S6_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(s7, TRAP_FRAME_S7_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(s8, TRAP_FRAME_S8_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(s9, TRAP_FRAME_S9_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(s10, TRAP_FRAME_S10_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(s11, TRAP_FRAME_S11_OFFSET);

TRAP_FRAME_ASSERT_OFFSET(t3, TRAP_FRAME_T3_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(t4, TRAP_FRAME_T4_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(t5, TRAP_FRAME_T5_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(t6, TRAP_FRAME_T6_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(sp, TRAP_FRAME_SP_OFFSET);

TRAP_FRAME_ASSERT_OFFSET(sepc, TRAP_FRAME_SEPC_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(sstatus, TRAP_FRAME_SSTATUS_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(scause, TRAP_FRAME_SCAUSE_OFFSET);
TRAP_FRAME_ASSERT_OFFSET(stval, TRAP_FRAME_STVAL_OFFSET);

TRAP_FRAME_ASSERT_OFFSET(reserved, TRAP_FRAME_RESERVED_OFFSET);

#undef TRAP_FRAME_ASSERT_OFFSET

void trap_init(void);
struct trap_frame *trap_handler(struct trap_frame *frame);

#endif
